### ISSUE TITLE
Infinite exp exploit

### ISSUE THREAD

**Issue by ThunderSmith** [Epoxide-MC/Enchanting-Plus#19]
Where should I report this?

**Comment by darkhax** [comment]
You should report this here. What version of the mod are you using? We fixed an infinite exploit in version 4 of the mod.

**Comment by ThunderSmith** [comment]
Looks like 3.0.2

**Comment by ThunderSmith** [comment]
It's in a mod, I can disclose details, but it makes last stand enchantment OP, and anything that uses exp really easy.

**Comment by ThunderSmith** [comment]
I was directed to here to report the problem so I assume it's not the mod curators fault.

**Comment by darkhax** [comment]
3.0.2 is extremely outdated. There have been many updates since then. I am not sure where you obtained the mod download from, however we are the mod curators and developers. The issue you are referring to has probably been patched. The exp issue I fixed was one where you could get an enchantment when you're at a low level, and then when you are at a high level the exp from disenchanting is worth more then when it was at the lower levels. Read this: https://github.com/Epoxide-MC/Enchanting-Plus/issues/4

**Comment by ThunderSmith** [comment]
Yup, exactly what I was referring too. So the mod pack needs to update its mod version. I'll tell the mod pack owner. Thank you!

**Comment by darkhax** [comment]
No problem.
