### ISSUE TITLE
[Request] Lower chest loot spawn chance

### ISSUE THREAD

**Issue by Zsashas** [Epoxide-MC/Enchanting-Plus#20]
As it currently is, a lot of the chests I find, as well as the bonus starting chest, are almost all scrolls, with almost nothing else in terms of loot. Being able to decrease the chance of getting scrolls in chests would be awesome.

As an example, I found 7 scrolls and a single stone pickaxe in one bonus chest, the next bonus chest was all scrolls.

**Comment by darkhax** [comment]
This is a really interesting issue, as the chance of getting a scroll in your chest is only twice that of a golden apple. The issue is that there is a new entry created for every enchantment within the game. Unfortunately we can't do anything about that currently. The best option would be to just drop scrolls as dungeon loot for now (with the exception of our custom villager chest), until a proper solution can be worked out.

**Comment by Zsashas** [comment]
But aren't the scrolls all one item with different NBT?

**Comment by darkhax** [comment]
Yes, they are a single item, however each enchantment requires a different NBT value to hold the enchantment. The issue with the current system is that each variation is added into the system separately so it dilutes everything else. There is probably a way to add special logic for this, @lclc98 should look into the entry object class to see if we can override something in there.

**Comment by Zsashas** [comment]
Well, how are normal enchanted books handled as loot?

**Comment by Zsashas** [comment]
Will there be an update soon? Also possibly add a config to stop scrolls from generating in chests at all? Have them only obtainable from mob drops in that case.
